[package]
name = "vulkano-samples"
version = "0.1.0"
authors = ["Benoit Eudier <benoit.eudier@gmail.com>"]
edition = "2018"

[dependencies]
vulkano = "0.11"
vulkano-shaders = "0.11"
winit = "0.18"
vulkano-win = "0.11"
tobj = "0.1.6"

